spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://bd-qaliwarma.postgres.database.azure.com:5432/qaliwarma?sslmode=require
    username: administrador
    password: Postgres2024
    driver-class-name: org.postgresql.Driver
