name: Build and deploy JAR app to Azure Web App - ms-qaliwarma

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: List files in build/libs
        run: ls -l build/libs

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: 'build/libs/qaliwarma_project-0.0.1-SNAPSHOT.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: List files in current directory
        run: ls -l

      - name: List files in downloaded artifact directory
        run: ls -l java-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8D4F97C13B9D4E079669F0C1E0622522 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_30C857E9290A4B4586BA3B03FFA61295 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F9572AF66A7A49D3BCF070758A28E366 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ms-qaliwarma'
          slot-name: 'Production'
          package: 'java-app/qaliwarma_project-0.0.1-SNAPSHOT.jar'
